apiVersion: v1
data:
  nginx.conf: "\n\nevents {\n  \n    }\n\n    http {\n    #upgrade required is coming\n\
    \    proxy_http_version 1.1;\n\n    log_format cus_format 'P_ARG: \"$arg_p\" -\
    \ P_UTM: \"$arg_utm_source\" - BACKENDHOST: \"$backend_host\" - SCHOST: \"$sc_host\"\
    \ - SCHOST2: \"$sc_host2\"  - REMOTEURL: \"$uri\" - INGRESS: \"$ingress\"';\n\
    \    \n\n    #remote_addr for nonlocalhost\n\n    #<PARSE SPLIT-LOGIC>\nsplit_clients\
    \ \"${msec}\" $variant1 {\n    55%   signup.nwc1.com;\n    25%   signup.nwc2.com;\n\
    \    20%   signup.nwc3.com;\n}\n\nsplit_clients \"${msec}\" $variant2 {\n    60%\
    \   signup.nwc1.com;\n    40%   signup.nwc2.com;\n}\n\nsplit_clients \"${msec}\"\
    \ $variant3 {\n    70%   signup.nwc1.com;\n    30%   signup.nwc2.com;\n}\n\nsplit_clients\
    \ \"${msec}\" $variant4 {\n    80%   signup.nwc1.com;\n    20%   signup.nwc2.com;\n\
    }\n\nsplit_clients \"${msec}\" $variant5 {\n    90%   signup.nwc1.com;\n    10%\
    \   signup.nwc2.com;\n}\n\nsplit_clients \"${msec}\" $ {\n}\n\n\n#</PARSE>\n \
    \  # use :var1:var2:var3: -> \"~^:.*:.*:.*:$\"\n   # now add conditions for each\
    \ var\n   # if want to match var1 can be 45 or 64 do \"~^:(45|64):.*:.*:$\"\n\n\
    \   # conditional splitting\n  \n  #<PARSE CONDS>\nif( $variant1 ~ \"(^64$)\"\
    \ ) {\n    set $variant $arg_p;\n    set $present true;\n}\n\nif( $variant2 ~\
    \ \"(^yahoo$)\" ) {\n    set $variant $arg_p;\n    set $present true;\n}\n\nif(\
    \ $variant1 ~ \"(^42$)\" ) {\n    set $variant $arg_utm_source;\n    set $present\
    \ true;\n}\n\nif( $variant4 ~ \"(^98$)\" ) {\n    set $variant $arg_utm_source;\n\
    \    set $present true;\n}\n\nif( $variant5 ~ \"(^98$)\" ) {\n    set $variant\
    \ $arg_p;\n    set $present true;\n}\n\n\n#</PARSE>\n\n    map \"$backend_host\"\
    \ $ingress{\n                default 10.133.0.163;\n                signup.nwc1.com\
    \ 10.133.0.180;\n                signup.nwc2.com 10.133.0.180;\n             \
    \ }\n\n\n    server {\n        listen 80;\n        server_name localhost;\n\n\
    \        location / {\n            return 200 \"LOCALHOST HOMEPAGE\";\n      \
    \  }\n    }\n\n    server {\n\n        \n\n        listen 80;\n        server_name\
    \ signup.nwc.com;\n\n        set $ingress1 10.133.0.180;\n        set $ingress2\
    \ 10.133.0.163;\n        \n        if ( $uri = \"/static/nwc1\"){\n          set\
    \ $ingress $ingress1;\n          set $backend_host signup.nwc1.com;\n        }\n\
    \n        if ( $uri = \"/static/nwc2\"){\n          set $ingress $ingress1;\n\
    \          set $backend_host signup.nwc2.com;\n        }\n\n        if ( $uri\
    \ = \"/static/nwc3\"){\n          set $ingress $ingress2;\n          set $backend_host\
    \ signup.nwc3.com;\n        }\n\n        location /static/nwc {\n            \
    \    \n                rewrite /static/.* / break;\n                proxy_pass\
    \ http://$ingress;\n                proxy_set_header Host $backend_host;\n   \
    \     \n        }\n\n\n        location / {\n\n           \n            set $backend_host\
    \ $variant;\n            \n            \n          \n             # no need to\
    \ set persistent to flask3\n            if ($backend_host != signup.nwc3.com){\n\
    \            add_header Set-Cookie \"persistent_backend=$backend_host\";\n   \
    \         }\n\n            proxy_pass http://$ingress;\n            proxy_set_header\
    \ Host $backend_host;\n            \n            \n        }\n\n        access_log\
    \ /var/log/nginx/access.log cus_format;\n    }\n    }\n"
kind: ConfigMap
metadata:
  name: nginx-config
